# -*- coding: utf-8 -*-
"""Exercise3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDOrneETo6pMVlajGsvNZlDo7fznvtpu
"""

def fizzbuzz():
  for i in range(1, 51):
    if i % 3 != 0 and i % 5 != 0:
      print(i)
    elif i % 3 == 0 and i % 5 == 0:
      print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
      print("Buzz")
    elif i % 3 == 0 and i % 5 == 0:
      print("FizzBuzz")

fizzbuzz()