# -*- coding: utf-8 -*-
"""Excersise4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-8IR6uKgHkj7KGMe0nsfD5NMVrUIo6dB
"""

def sum(n):
    i = 1
    s = 0.0
    for i in range(1, n+1):
        s = s + 1/i;
    return s;
n = int(input())
print("The Harmonic Sum Up To", 10, "=", round(sum(n), 6))