# -*- coding: utf-8 -*-
"""Multiplication2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBBB-4pc65lv1TCCTNWWbFzVdMcvZblI
"""

def printFun(x):
  for i in range(x+1):
    if i == 0:
      print(" ", 1, 2, 3, 4, sep=' | ')
    if i > 0:
      print(1*i, 1*i, 2*i, 3*i, 4*i, sep=' | ')
x = int(input())
printFun(x)